import readline from 'readline';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..', '..');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q, fallback = '') =>
  new Promise(resolve => rl.question(q, ans => resolve(ans.trim() || fallback)));

function rand(len = 16) {
  return Math.random().toString(36).slice(2, 2 + len) + Math.random().toString(36).slice(2, 2 + len);
}

async function setup() {
  console.log('\n🤖  Personal AI Assistant — Setup Wizard');
  console.log('────────────────────────────────────────\n');

  // ── User identity ────────────────────────────────────────────────────────
  const name      = await ask('Your name (used in the bot\'s personality): ');
  const timezone  = await ask('Timezone (e.g. Asia/Kolkata) [Asia/Kolkata]: ', 'Asia/Kolkata');
  const ownerTgId = await ask('Your Telegram user ID (send /id to @userinfobot to find it): ');

  // ── Telegram ─────────────────────────────────────────────────────────────
  console.log('\n── Telegram (create bot at @BotFather → /newbot) ──');
  const botToken    = await ask('Bot Token: ');
  const webhookUrl  = await ask('Webhook URL (leave blank for local dev): ');
  const webhookSecret = rand(24);

  // ── Groq ──────────────────────────────────────────────────────────────────
  console.log('\n── Groq API (free at console.groq.com) ──');
  const groqKey = await ask('Groq API Key: ');

  // ── Firebase ──────────────────────────────────────────────────────────────
  console.log('\n── Firebase (free at console.firebase.google.com) ──');
  console.log('   Project Settings → Service Accounts → Generate New Private Key\n');
  const fbProjectId   = await ask('Firebase Project ID: ');
  const fbKeyId       = await ask('Firebase Private Key ID: ');
  const fbPrivateKey  = await ask('Firebase Private Key (paste full -----BEGIN...END----- block): ');
  const fbClientEmail = await ask('Firebase Client Email: ');
  const fbClientId    = await ask('Firebase Client ID: ');

  // ── Firebase Web App config (dashboard) ──────────────────────────────────
  console.log('\n── Firebase Web App config (for the dashboard) ──');
  console.log('   Firebase Console → Project Settings → Your apps → Web app → SDK config\n');
  const fbWebApiKey         = await ask('Web API Key: ');
  const fbWebAuthDomain     = await ask('Auth Domain (e.g. project.firebaseapp.com): ');
  const fbWebDatabaseUrl    = await ask('Database URL (press Enter to skip): ');
  const fbWebStorageBucket  = await ask('Storage Bucket (e.g. project.firebasestorage.app): ');
  const fbWebSenderId       = await ask('Messaging Sender ID: ');
  const fbWebAppId          = await ask('App ID (e.g. 1:123:web:abc): ');

  // ── Google Calendar (optional) ────────────────────────────────────────────
  console.log('\n── Google Calendar (optional — press Enter to skip) ──');
  const gcClientId     = await ask('Google OAuth Client ID [skip]: ');
  const gcClientSecret = await ask('Google OAuth Client Secret [skip]: ');
  const gcRedirectUri  = await ask('Google OAuth Redirect URI [skip]: ');

  // ── Voice API key ─────────────────────────────────────────────────────────
  const voiceKey = rand(20);

  // ── Dashboard URL ─────────────────────────────────────────────────────────
  const dashUrl = await ask('\nDashboard URL (leave blank if not deployed yet): ', '');

  rl.close();

  // ── Write .env ────────────────────────────────────────────────────────────
  const envLines = [
    '# === PERSONAL AI ASSISTANT — generated by setupWizard.js ===',
    '',
    '# Telegram',
    `TELEGRAM_BOT_TOKEN=${botToken}`,
    `TELEGRAM_WEBHOOK_URL=${webhookUrl}`,
    `TELEGRAM_WEBHOOK_SECRET=${webhookSecret}`,
    '',
    '# Groq',
    `GROQ_API_KEY=${groqKey}`,
    'LLM_PROVIDER=groq',
    '',
    '# Firebase Admin SDK (backend)',
    `FIREBASE_PROJECT_ID=${fbProjectId}`,
    `FIREBASE_PRIVATE_KEY_ID=${fbKeyId}`,
    `FIREBASE_PRIVATE_KEY="${fbPrivateKey}"`,
    `FIREBASE_CLIENT_EMAIL=${fbClientEmail}`,
    `FIREBASE_CLIENT_ID=${fbClientId}`,
    '',
    '# Firebase Web App (dashboard — VITE_ prefix required)',
    `VITE_FIREBASE_API_KEY=${fbWebApiKey}`,
    `VITE_FIREBASE_AUTH_DOMAIN=${fbWebAuthDomain}`,
    `VITE_FIREBASE_DATABASE_URL=${fbWebDatabaseUrl}`,
    `VITE_FIREBASE_PROJECT_ID=${fbProjectId}`,
    `VITE_FIREBASE_STORAGE_BUCKET=${fbWebStorageBucket}`,
    `VITE_FIREBASE_MESSAGING_SENDER_ID=${fbWebSenderId}`,
    `VITE_FIREBASE_APP_ID=${fbWebAppId}`,
    '',
    '# Google Calendar (optional)',
    `GOOGLE_CLIENT_ID=${gcClientId}`,
    `GOOGLE_CLIENT_SECRET=${gcClientSecret}`,
    `GOOGLE_REDIRECT_URI=${gcRedirectUri}`,
    '',
    '# User details',
    `USER_NAME=${name}`,
    `USER_TIMEZONE=${timezone}`,
    `OWNER_TELEGRAM_ID=${ownerTgId}`,
    `VITE_USER_ID=${ownerTgId}`,
    `DASHBOARD_URL=${dashUrl}`,
    `VITE_API_BASE=${webhookUrl ? webhookUrl.replace(/\/webhook$/, '') : ''}`,
    `VITE_VOICE_API_KEY=${voiceKey}`,
    '',
    '# Voice API',
    `VOICE_API_KEY=${voiceKey}`,
    '',
    '# Server',
    'NODE_ENV=development',
    'PORT=8080',
  ].join('\n');

  fs.writeFileSync(path.join(ROOT, '.env'), envLines + '\n');
  console.log('\n✅  .env written');

  // ── Write user-config.json ────────────────────────────────────────────────
  const config = {
    name,
    timezone,
    ownerTelegramId: ownerTgId,
    dashboardUrl: dashUrl,
    createdAt: new Date().toISOString()
  };
  fs.writeFileSync(path.join(ROOT, 'user-config.json'), JSON.stringify(config, null, 2) + '\n');
  console.log('✅  user-config.json written');

  // ── Summary ───────────────────────────────────────────────────────────────
  console.log(`
────────────────────────────────────────
🎉  Setup complete for ${name}!

Next steps:
  1.  npm install
  2.  npm run dev
  3.  In another terminal: ngrok http 8080
  4.  Copy the ngrok https URL
  5.  Edit .env → set TELEGRAM_WEBHOOK_URL=<ngrok-url>
  6.  node backend/setup/setupWebhook.js
  7.  Open Telegram → message your bot!

Your Voice API key: ${voiceKey}
────────────────────────────────────────
`);
}

setup().catch(err => {
  console.error('Setup failed:', err.message);
  process.exit(1);
});
